name: sailor-pipeline-minimal
channels:
  - bioconda
  - conda-forge

dependencies:
  # Essential workflow tools
  - nextflow>=22.10.0
  - python=3.9
  - pip
  
  # Core bioinformatics tools
  - star>=2.7.9a
  - samtools>=1.15
  - bcftools>=1.15
  - gatk4>=4.3.0
  - picard>=2.27.0
  
  # Quality control
  - fastp>=0.23.0
  - fastqc>=0.11.9
  - multiqc>=1.12
  - qualimap>=2.2.2
  
  # Read counting
  - htseq>=2.0.0
  - featurecounts>=2.0.0
  
  # Variant processing
  - vcftools>=0.1.16
  - bedtools>=2.30.0
  - tabix>=1.11
  
  # R and DESeq2
  - r-base>=4.1.0
  - bioconductor-deseq2
  - r-ggplot2
  - r-dplyr
  - r-argparse
  
  # Python packages
  - numpy
  - pandas
  - pysam>=0.19.0
  - pybedtools
  
  # System utilities
  - openjdk>=8
  - parallel